import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from './components/Header';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body>
        <Header /> {/* Adicione seu componente Header aqui */}
        <main className="pt-16"> {/* Adicione um padding-top para o conteúdo não ficar por baixo do header fixo */}
          {children} {/* Isso renderiza o conteúdo da sua page.tsx e outras rotas */}
        </main>
      </body>
    </html>
  );
}

